(* ::Package:: *)

BeginPackage["CasimirRFM`"];

	(* GROUP FUNCTIONS *)
	DefGenerator::usage = "DefGenerator[\!\(M\),\!\(\[Sigma]g\)] defines the generator g = \!\(\*RowBox[{\"{\", RowBox[{\"\\\"\\\\!\\\\(\\\\*SubscriptBox[\\\\(D\\\\), \\\\(g\\\\)]\\\\)\\\"\", \",\", \"\\\"\\\\!\\\\(\\\\*SubscriptBox[OverscriptBox[\\\\(b\\\\), \\\\(\[RightArrow]\\\\)], \\\\(g\\\\)]\\\\)\\\"\", \",\", \"\\\"\\\\!\\\\(\\\\*SubscriptBox[\\\\(\[Sigma]\\\\), \\\\(g\\\\)]\\\\)\\\"\"}], \"}\"}]\) from matrix \!\( M = \*TagBox[RowBox[{\"(\", \"\[NoBreak]\", GridBox[{{\"\\\"\\\\!\\\\(\\\\*SubscriptBox[\\\\(D\\\\), \\\\(g\\\\)]\\\\)\\\"\", \"\\\"\\\\!\\\\(\\\\*SubscriptBox[OverscriptBox[\\\\(b\\\\), \\\\(\[RightArrow]\\\\)], \\\\(g\\\\)]\\\\)\\\"\"}, {\"0\", \"1\"}}, Rule[RowSpacings, 1], Rule[ColumnSpacings, 1], Rule[RowAlignments, Baseline], Rule[ColumnAlignments, Center]], \"\[NoBreak]\", \")\"}], Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\) and spin lift specified by \!\(\*SuperscriptBox[\(e\), \(2  \[Pi]\[ImaginaryI] \*SubscriptBox[\(\[Sigma]\), \(g\)]\)]\) = \[PlusMinus]1 (\!\(\*SubscriptBox[\(\[Sigma]\), \(g\)]\) = 0 by default).";	
	ActsFreelyQ::usage = "ActsFreelyQ[\[CapitalGamma]] returns \!\(\*StyleBox[\"True\",\nFontWeight->\"Bold\"]\) if every non-identity element of \[CapitalGamma] acts freely on \!\(\*SuperscriptBox[\(T\), \(k\)]\) coordinates z, checking whether g\[CenterDot]z=z has non-trivial solutions.";
	ElementAction::usage = "ElementAction[g][z] acts with element g on the vector z.";
	ComposeElements::usage = "ComposeElements[\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\)] composes the elements \!\(\*SubscriptBox[\(g\), \(1, 2\)]\) = {\!\(\*SubscriptBox[\(D\), SubscriptBox[\(g\), \(1, 2\)]]\), \!\(\*SubscriptBox[\(\!\(\*OverscriptBox[\(b\), \(\[RightArrow]\)]\)\), SubscriptBox[\(g\), \(1, 2\)]]\), \!\(\*SubscriptBox[\(\[Sigma]\), SubscriptBox[\(g\), \(1, 2\)]]\)} as \!\(\*SubscriptBox[\(g\), \(1\)]\)\[SmallCircle]\!\(\*SubscriptBox[\(g\), \(2\)]\) = {\!\(\*SubscriptBox[\(D\), SubscriptBox[\(g\), \(1\)]]\)\[CenterDot]\!\(\*SubscriptBox[\(D\), SubscriptBox[\(g\), \(2\)]]\) , \!\(\*SubscriptBox[\(D\), SubscriptBox[\(g\), \(1\)]]\)\[CenterDot]\!\(\*SubscriptBox[\(\!\(\*OverscriptBox[\(b\), \(\[RightArrow]\)]\)\), SubscriptBox[\(g\), \(2\)]]\) + \!\(\*SubscriptBox[\(\!\(\*OverscriptBox[\(b\), \(\[RightArrow]\)]\)\), SubscriptBox[\(g\), \(1\)]] mod \!\(\*SuperscriptBox[\(\[DoubleStruckCapitalZ]\), \(k\)]\)\), \!\(\*SubscriptBox[\(\[Sigma]\), SubscriptBox[\(g\), \(1\)]]\) + \!\(\*SubscriptBox[\(\[Sigma]\), SubscriptBox[\(g\), \(2\)]]\) mod \[DoubleStruckCapitalZ]}.";
	ElementOrder::usage = "ElementOrder[g] returns the order k of the element g such that \!\(\*SuperscriptBox[\(g\), \(k\)]\) = \[DoubleStruckOne]. It takes g as an affine torus isometry, not taking into account the spin lift (which might therefore be omitted).";
	ElementOrder::arg = "The input of \!\(\*StyleBox[\"ElementOrder\",\nFontWeight->\"Bold\"]\) is a generator g = {\!\(\*SubscriptBox[\(D\), \(g\)]\),\!\(\*SubscriptBox[\(b\), \(g\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(g\)]\)} (the spin lift \!\(\*SubscriptBox[\(\[Sigma]\), \(g\)]\) might be omitted).";
	ElementOrder::iter = "Element order could not be determined within `1` compositions.";
	GetAllowedShifts::usage = "GetAllowedShifts[\!\(Dg\)] returns the shift vectors \!\(\*SubscriptBox[OverscriptBox[\(b\), \(\[RightArrow]\)], \(g\)]\) satisfying \!\(\*SubscriptBox[\(D\), \(g\)]\)\[CenterDot]\!\(\*SubscriptBox[OverscriptBox[\(b\), \(\[RightArrow]\)], \(g\)]\) = \!\(\*SubscriptBox[OverscriptBox[\(b\), \(\[RightArrow]\)], \(g\)] mod \!\(\*SubscriptBox[\(\[CapitalLambda]\), \(\[Perpendicular]\)]\)\), i.e. leaving the space group fixed-point-free given the point group generator \!\(\*SubscriptBox[\(D\), \(g\)]\).";
	GetGroup::usage = "GetGroup[{\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\),...}] returns the finite group generated by {\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\),...}."; 
	GetGroup::arg = "The input of \!\(\*StyleBox[\"GetGroup\",\nFontWeight->\"Bold\"]\) is a list of generators {g} = {{\!\(\*SubscriptBox[\(D\), \(g\)]\),\!\(\*SubscriptBox[\(b\), \(g\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(g\)]\)}, ...}."
	GetGroup::iter = "Group closure was not reached within `1` iterations.";
	NormalizerQ::usage = "NormalizerQ[\[CapitalGamma],{Q,q}] checks whether the transformation \!\(\*OverscriptBox[\(z\), \(\[RightArrow]\)]\)\[RightArrow] Q \!\(\*OverscriptBox[\(z\), \(\[RightArrow]\)]\)+\!\(\*OverscriptBox[\(q\), \(\[RightArrow]\)]\) is in the normalizer of group \[CapitalGamma]. If not, it also checks whether Q is in the normalizer of the point group.";
	NormalizerQ::arg = "The input of \!\(\*StyleBox[\"NormalizerQ[\[Gamma],{Q,q}]\",\nFontWeight->\"Bold\"]\) is a group \!\(\[Gamma]\), a matrix Q and a vector q."
	CasimirBranes::usage = "CasimirBranes[g] returns the coordinates of the Casimir branes associated to group element g.";
	CasimirBranes::arg = "The input of \!\(\*StyleBox[\"CasimirBranes\",\nFontWeight->\"Bold\"]\) is an element g = {\!\(\*SubscriptBox[\(D\), \(g\)]\),\!\(\*SubscriptBox[OverscriptBox[\(b\), \(\[RightArrow]\)], \(g\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(g\)]\)}.";
	
	GetInvariantForms::usage = "GetInvariantForms[generatorList] returns a basis of p-forms invariant under the action of the group with generators \!\(\*StyleBox[\"generatorList\",\nFontSlant->\"Italic\"]\) = {\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\),...}, in the form {Betti numbers, List of invariant p-forms, List of p-form coefficients}. The form coefficients are given as a list of rules that can be used to define a SparseArray[coefficients\[LeftDoubleBracket]p+1\[RightDoubleBracket], ConstantArray[k,p]] encoding the components of a p-form on a k-dimensional space.";
	GetInvariantMetric::usage = "GetInvariantMetric[generatorList] returns the invariant metric G and geometric moduli {\!\(\*SubscriptBox[\(c\), \(1\)]\),\!\(\*SubscriptBox[\(c\), \(2\)]\),...} from a list of generators \!\(\*StyleBox[\"generatorList\",\nFontSlant->\"Italic\"]\) = {\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\),...} in the form {number of moduli, {\!\(\*SubscriptBox[\(c\), \(1\)]\),\!\(\*SubscriptBox[\(c\), \(2\)]\),...},G}.";
	GetModuliSpaceMetric::usage = "GetModuliSpaceMetric[\[DoubleStruckCapitalD],G,{\!\(\*SubscriptBox[\(\[Phi]\), \(i\)]\)},\!\(\*StyleBox[\"print\",\nFontSlant->\"Italic\"]\)] returns the metric on the moduli space parametrised by the RFM moduli {\!\(\*SubscriptBox[\(\[Phi]\), \(i\)]\)}; set print=True to print kinetic terms (print=False by default).";
	GetModuliSpaceMetric::dim = "The compactified theory must have dimension d = D-k > 2, for a compactification of a D-dimensional theory on a k-dimensional compact space.";
	SpinStructures::usage = "SpinStructures[\!\(\*StyleBox[\"generatorList\",\nFontSlant->\"Italic\"]\)] returns the most general spin structure on the RFM with generators \!\(\*StyleBox[\"generatorList\",\nFontSlant->\"Italic\"]\) = {\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\),...} in terms of a vector \!\(\*OverscriptBox[\(h\), \(\[RightArrow]\)]\) = {\!\(\*SubscriptBox[\(h\), \(1\)]\),...,\!\(\*SubscriptBox[\(h\), \(k\)]\)} encoding the fermion boundary conditions compatible with the quotient \!\(\*SuperscriptBox[\(T\), \(k\)]\)/\[CapitalGamma], where \[CapitalGamma] is the finite group generated by {\!\(\*SubscriptBox[\(g\), \(1\)]\),\!\(\*SubscriptBox[\(g\), \(2\)]\),...}. The output is the Association <|\"GeneralForm\" \[Rule] {\!\(\*SubscriptBox[\(h\), \(1\)]\),...,\!\(\*SubscriptBox[\(h\), \(k\)]\)},\"Allowed\" \[Rule] List of allowed structures|>.";
	SpinStructures::arg = "The input of \!\(\*StyleBox[\"SpinStructures\",\nFontWeight->\"Bold\"]\) is a list of elements {g} = {{\!\(\*SubscriptBox[\(D\), \(g\)]\),\!\(\*SubscriptBox[\(b\), \(g\)]\),\!\(\*SubscriptBox[\(\[Sigma]\), \(g\)]\)}, ...}."
	
	(* CYCLIC GROUP FUNCTIONS *)
	GetCompanionMatrix::usage = "GetCompanionMatrix[p,x] returns the companion matrix of the polynomial p(x) in the form of a SparseArray.";
	FiniteOrderMatrices::usage = "FiniteOrderMatrices[k] returns representatives up to conjugacy by GL(k,\[DoubleStruckCapitalQ]) of all finite order k*k matrices, built out of direct sums of companion matrices of cyclotomic polynomials; the output is a list of pairs {order,matrix}.";
	
	(* TRACE FUNCTIONS *)	
	TraceSym::usage = "TraceSym[g,\[DoubleStruckCapitalD]] computes the trace of element g in the symmetric (graviton) representation of SO(\[DoubleStruckCapitalD]-2).";
	TraceForm::usage = "TraceForm[k,g,\[DoubleStruckCapitalD]] computes the trace of element g in the antisymmetric p-form representation of SO(\[DoubleStruckCapitalD]-2).";
	TraceSpinor::usage = "TraceSpinor[g,\[DoubleStruckCapitalD],Weyl] computes the trace of element g in the spinor representation of SO(\[DoubleStruckCapitalD]-2), given the choice of spin lift of g. Set \!\(\*StyleBox[\"Weyl\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"=\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"True\",\nFontWeight->\"Bold\"]\) for a Weyl spinor (\!\(\*StyleBox[\"Weyl\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"=\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"False\",\nFontWeight->\"Bold\"]\) by default; note that Weyl spinors only exist in even dimension).";
	TraceRS::usage = "TraceRS[g,\[DoubleStruckCapitalD],Weyl] computes the trace of element g in the vector-spinor (Rarita-Schwinger) representation of SO(\[DoubleStruckCapitalD]-2), given the choice of spin lift of g. Set \!\(\*StyleBox[\"Weyl\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"=\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"True\",\nFontWeight->\"Bold\"]\) for a Weyl spinor (\!\(\*StyleBox[\"Weyl\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"=\",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\" \",\nFontWeight->\"Bold\"]\)\!\(\*StyleBox[\"False\",\nFontWeight->\"Bold\"]\) by default; note that Weyl spinors only exist in even dimension).";
	TraceBosons::usage = "TraceBosons[\!\(\*StyleBox[\"bosons\",\nFontSlant->\"Italic\"]\),g,\[DoubleStruckCapitalD]] computes the trace of the element g \[Element] \[CapitalGamma] under the bosonic representations listed in \!\(\*StyleBox[\"bosons\",\nFontSlant->\"Italic\"]\) in \[DoubleStruckCapitalD] dimensions. See documentation for details on spectrum syntax.";
	TraceBosons::arg = "The input of TraceBosons[bosons,g,D] is a list of bosons (Associations), an element g of the form {D,b,\[Sigma]} and the dimension D."
	TraceBosons::type = "Unknown bosonic field type `1`. Valid types are \"Graviton\", \"Scalar\", and \"Form\".";
	TraceFermions::usage = "TraceFermions[\!\(\*StyleBox[\"fermions\",\nFontSlant->\"Italic\"]\),g,\[DoubleStruckCapitalD]] computes the trace of the element g \[Element] \[CapitalGamma] under the fermionic representations listed in \!\(\*StyleBox[\"fermions\",\nFontSlant->\"Italic\"]\) in \[DoubleStruckCapitalD] dimensions, given the choice of spin lift of g. See documentation for details on spectrum syntax.";
	TraceFermions::arg = "The input of TraceFermions[fermions,g,D] is a list of fermions (Associations), an element g of the form {D,b,\[Sigma]} and the dimension D."
	TraceFermions::type = "Unknown fermionic field type `1`. Valid types are \"Spinor\" and \"Gravitino\".";
	
	(* LATTICE SUMS FUNCTIONS *)
	Ewald::usage = "Ewald[c,h,s,\[Alpha],G,\[Epsilon]] numerically computes the lattice sum \!\(\*UnderscriptBox[\"\[Sum]\", RowBox[{OverscriptBox[StyleBox[\"n\", \"TI\"], \"\[RightVector]\"], \"\[Element]\", StyleBox[\"Z\", FontSlant->\"Plain\"]}]]\) \!\(\*FractionBox[SuperscriptBox[StyleBox[\"e\", \"TI\"], RowBox[{\"2\", \"\[Pi]\", StyleBox[\"i\", \"TI\"], \" \", OverscriptBox[StyleBox[\"h\", \"TI\"], \"\[RightVector]\"], \"\[CenterDot]\", OverscriptBox[StyleBox[\"n\", \"TI\"], \"\[RightVector]\"]}]], RowBox[{\"|\", OverscriptBox[StyleBox[\"n\", \"TI\"], \"\[RightVector]\"], \"+\", OverscriptBox[StyleBox[\"c\", \"TI\"], \"\[RightVector]\"], SubsuperscriptBox[\"|\", StyleBox[\"G\", \"TI\"], RowBox[{\"2\", StyleBox[\"s\", \"TI\"]}]]}]]\); \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"]\) controls the estimated truncation of the numerical sums such that \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-p\)]\) targets roughly \!\(\*StyleBox[\"p\", \"TI\"]\) decimal digits. The parameter \[Alpha] controls the split between the real and reciprocal sums in the Ewald summation method.";
	ReducedLatticeSum::usage = "ReducedLatticeSum[\[DoubleStruckCapitalD],g,h,G,\[Epsilon]] computes the lattice sum numerically, projecting onto the g-invariant lattice, i.e. collapsing the sum to the lowest dimension possible, before numerically summing using the Ewald summation method. The lattice sum corresponds (up to a numerical factor) to the contribution to the D-dimensional Casimir potential of element g on a background with metric G and fermion boundary conditions \!\(\*OverscriptBox[\(h\), \(\[RightArrow]\)]\) = {\!\(\*SubscriptBox[\(h\), \(1\)]\),...,\!\(\*SubscriptBox[\(h\), \(k\)]\)}; \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"]\) controls the estimated truncation of the numerical sums such that \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-p\)]\) targets roughly \!\(\*StyleBox[\"p\", \"TI\"]\) decimal digits (\!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-4\)]\) by default).";
	ReducedLatticeSum::metric = "The compactification metric must be real, symmetric, and positive definite.";
	TracedSum::usage="TracedSum[\[DoubleStruckCapitalD],g,spectrum,h,G,\[Phi],\[Epsilon]] computes the lattice sum numerically, summing over all representations in the spectrum taking into account the appropriate traces of element g.  \[FilledSquare] \[DoubleStruckCapitalD] = dimension of theory;  \[FilledSquare] \!\(\*StyleBox[\"spectrum\",FontWeight->\"Bold\"]\) = {bosons,fermions} (see documentation for details on spectrum syntax); \[FilledSquare] \!\(\*StyleBox[\"h\",FontWeight->\"Bold\"]\) = {\!\(\*SubscriptBox[\(h\), \(1\)]\),...,\!\(\*SubscriptBox[\(h\), \(k\)]\)} = spin structure/default fermion boundary conditions; \!\(\*SubscriptBox[\(h\), \(i\)] = 0\) for periodic boundary conditions around direction i, \!\(\*SubscriptBox[\(h\), \(i\)]\) = \!\(\*FractionBox[\(1\), \(2\)]\) for anti-periodic;  \[FilledSquare] \!\(\*StyleBox[\"G\",FontWeight->\"Bold\"]\) = metric on the compact space; generally a function of the moduli G(\!\(\*SubscriptBox[\(c\), \(1\)]\),...,\!\(\*SubscriptBox[\(c\), \(m\)]\));  \[FilledSquare] \!\(\*StyleBox[\"\[Phi]\",FontWeight->\"Bold\"]\) = {\!\(\*SubscriptBox[\(c\), \(i\)]\) \[RightArrow] \!\(\*SubscriptBox[OverscriptBox[\(c\), \(_\)], \(i\)]\)} = moduli values given as replacement rule (point in moduli space where the sum is evaluated numerically);  \[FilledSquare] \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"]\) controls the estimated truncation of the numerical sums such that \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-p\)]\) targets roughly \!\(\*StyleBox[\"p\", \"TI\"]\) decimal digits (\!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-4\)]\) by default).";
	TracedSum::metric = "The compactification metric must be real, symmetric, and positive definite.";
	
	(* CASIMIR POTENTIAL FUNCTIONS *)
	CasimirPotential::usage = "CasimirPotential[\[DoubleStruckCapitalD],\[CapitalGamma],spectrum,h,G,\!\(\*SubscriptBox[\(\[Phi]\), \(0\)]\),\[Epsilon]] computes the Casimir potential \!\(\*SubscriptBox[\(V\), \(Cas\)]\)(\!\(\*SubscriptBox[\(\[Phi]\), \(0\)]\)) summing over all elements \[Gamma] \[Element] \[CapitalGamma], all lattice sums, including traces over all representations in the \!\(\*StyleBox[\"spectrum\",\nFontSlant->\"Italic\"]\), and the appropriate numerical factors for each element, with default fermion boundary conditions given by the spin structure vector \!\(\*OverscriptBox[\(h\), \(\[Rule]\)] = {\*SubscriptBox[h, 1],...,\*SubscriptBox[h, k]}\) and evaluated at the point \!\(\*SubscriptBox[\(\[Phi]\), \(0\)]\) in moduli space given as the replacement rule {\!\(\*SubscriptBox[\(\[Phi]\), \(i\)]\) \[Rule] \!\(\*SubscriptBox[OverscriptBox[\(\[Phi]\), \(_\)], \(i\)]\)}; \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"]\) controls the estimated truncation of the numerical sums such that \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-p\)]\) targets roughly \!\(\*StyleBox[\"p\", \"TI\"]\) decimal digits (\!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-4\)]\) by default).";
	CasimirEnergyDensity::usage = "CasimirEnergyDensity[\[DoubleStruckCapitalD],\[CapitalGamma],spectrum,h,G,\!\(\*SubscriptBox[\(\[Phi]\), \(0\)]\),z,\[Epsilon]] computes the D-dimensional Casimir energy density \!\(\*SubscriptBox[\(\[Rho]\), \(Cas\)]\)(\!\(\*OverscriptBox[\(z\), \(\[RightArrow]\)]\)) at point \!\(\*OverscriptBox[\(z\), \(\[RightArrow]\)]\[Element]\*SuperscriptBox[\(T\), \(k\)]\), summing over all elements \[Gamma]\[Element]\[CapitalGamma], all lattice sums, including traces over all representations in the \!\(\*StyleBox[\"spectrum\",\nFontSlant->\"Italic\"]\), and the appropriate numerical factors for each element, with default fermion boundary conditions given by the spin structure vector \!\(\*OverscriptBox[\(h\), \(\[Rule]\)]\) = {\*SubscriptBox[h, 1],...,\*SubscriptBox[h, k]} and evaluated at the point \*SubscriptBox[\[Phi], 0] in moduli space given as the replacement rule {\*SubscriptBox[\[Phi], i] \[Rule] \*SubscriptBox[OverscriptBox[\(\[Phi]\), \(_\)], i]}; \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"]\) controls the estimated truncation of the numerical sums such that \!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-p\)]\) targets roughly \!\(\*StyleBox[\"p\", \"TI\"]\) decimal digits (\!\(\*StyleBox[\"\[Epsilon]\", \"TI\"] = \*SuperscriptBox[10,\(-4\)]\) by default).";
	CasimirEnergyDensity::metric = "The compactification metric must be real, symmetric, and positive definite.";
	
	RFMGrad::usage="RFMGrad[f,x,dx] computes a numerical approximation of the normalised gradient (\!\(\*SubscriptBox[\(\[PartialD]\), \(i\)]\)f)/f evaluated at x.  It takes the option dx for the small displacement f(x + dx), which can be a number common to all directions or a numerical vector matching the dimension of x \[LongDash] the default value is dx = \!\(\*SuperscriptBox[\(10\), \(-4\)]\).";
	RFMHessian::usage="RFMHessian[f,x,dx] computes a numerical approximation of the Hessian matrix \!\(\*SubscriptBox[\(\[PartialD]\), \(i\)]\)\!\(\*SubscriptBox[\(\[PartialD]\), \(j\)]\)f evaluated at x.  It takes the option dx for the small displacement f(x + dx), which can be a number common to all directions or a numerical vector matching the dimension of x \[LongDash] the default value is dx = \!\(\*SuperscriptBox[\(10\), \(-4\)]\).";
	RFMHessian::arg = "The 3rd argument of \!\(\*StyleBox[\"RFMHessian\",\nFontWeight->\"Bold\"]\) must be a number x or a numerical vector \!\(\*StyleBox[OverscriptBox[StyleBox[\"dx\",\nFontWeight->\"Plain\"], \"\[RightArrow]\"],\nFontWeight->\"Plain\"]\) matching the dimension of x.";

Begin["`Private`"]
	(**)
	(**) (* GROUP FUNCTIONS *)
	(**)
	Clear[DefGenerator]
	DefGenerator[M_,lift_:0]:={M[[;;-2,;;-2]],M[[;;-2,-1]],lift//Mod[#,1]&};
	
	Clear[ActsFreelyQ];
	ActsFreelyQ[group_]:=Module[{k=Length[First[group][[1]]],zvec,znew},
		zvec = Array[z,k];
		For[j=1,j<=Length[group],j++,
			znew=ElementAction[group[[j]]][zvec]//Mod[#,1]&;
			If[group[[j]][[1]]!=IdentityMatrix[k],
				If[Length[Quiet@Solve[znew==zvec,zvec,Reals]]>0,
				Return[False]]
			];
		];
		Return[True];
	]
	
	Clear[ElementAction];
	ElementAction[g_][z_]:=(g[[1]] . z + g[[2]])
	
    Clear[ComposeElements];
    ComposeElements[g1_,g2_]:={g1[[1]] . g2[[1]], Mod[g1[[2]]+g1[[1]] . g2[[2]],1], g1[[3]]+g2[[3]]//Mod[#,1]&};
    
    Clear[ElementOrder];
	ElementOrder[g_List]:=Module[{id,el,res,k,count=1,maxCount=10^4},
		If[MatchQ[g,{_?MatrixQ,_?VectorQ,_?NumericQ}],
			el = g;,
			If[MatchQ[g,{_?MatrixQ,_?VectorQ}],
				el = Append[g,0],
				Message[ElementOrder::arg];
				Return[$Failed]
				];
			];
			
		k=Length[First@g];
		id={IdentityMatrix[k],ConstantArray[0,k]};
		res=el;
		While[!(res[[;;2]]===id),
			If[count>maxCount,
				Message[ElementOrder::iter,maxCount];
				Return[$Failed]
			];
			res = ComposeElements[el,res];
			count++
		];
		Return[count]
	];
	
	Clear[GetAllowedShifts];
	GetAllowedShifts[Dg_]:=Block[{bg=Array[b,Length@Dg],b,vars,order=ElementOrder[{Dg,ConstantArray[0,Length@Dg],0}],p=Global`p,subspace},
		subspace=(Array[p,Length[#]] . #&)@((#[[2]]&/@(Cases[#,{0,_}]&@(Transpose@Eigensystem[(IdentityMatrix[Length[#]]-#)])))&@Dg);
		bg=MapIndexed[If[#===0,b[#2[[1]]],#]&,subspace];
		vars=Cases[bg,b[_]];
		bg/order/.Solve[(IdentityMatrix[Length[Dg]]-Dg) . bg==0,vars,Modulus->order]/.p[a_]:>Subscript[p, a]
	];

	Clear[GetGroup]
	GetGroup[gens_List] := Module[{G, new, group, maxIterations=10^3},
		If[!AllTrue[gens, MatchQ[#, {_?MatrixQ, _?VectorQ, _?NumericQ}] &],
			Message[GetGroup::arg];
			Return[$Failed]
		];
		G = DeleteDuplicates[{#[[1]],Mod[#[[2]],1],#[[3]]}&/@gens, SameQ];
		
		group = FixedPointList[
			Function[h,
				new = DeleteDuplicates[Flatten[Outer[ComposeElements,gens,h,1], 1],SameQ];
				DeleteDuplicates[Join[h, new], SameQ]
			],G,maxIterations];
		If[!SameQ[group[[-1]],group[[-2]]],
			Message[GetGroup::iter,maxIterations];
			Return[$Failed]];
		Last[group]
	]

	Clear[NormalizerQ];
	NormalizerQ[group_List,{Q_?MatrixQ,q_?VectorQ}]:=Module[{newgroup,oldgroup=(#[[;;-2]]&/@group),check},
		If[!(AllTrue[group, MatchQ[#, {_?MatrixQ, _?VectorQ, _?NumericQ}] &]&&MatchQ[{Q,q},{_?MatrixQ, _?VectorQ}]),
			Message[NormalizerQ::arg];
			Return[$Failed]
		];
		newgroup={Q . #[[1]] . Inverse[Q], Q . #[[2]] + q - (Q . #[[1]] . Inverse[Q]) . q//Mod[#,1]&}&/@oldgroup;
		check=(Sort[newgroup]==Sort[oldgroup]);
		If[check==True,
			Return[check],
			If[Sort[(#[[1]]&/@newgroup)]==Sort[(#[[1]]&/@oldgroup)],Return["True for point group only."],
			False]
		];
	];
	
	Clear[CasimirBranes];
	CasimirBranes[el_]:=Module[{z=Global`z,y,U,D,V,tuples,branes},
		If[!MatchQ[el,{_?MatrixQ,_?VectorQ,_}],
			Message[CasimirBranes::arg];
			Return[$Failed];
		];
		{U,D,V}=SmithDecomposition[IdentityMatrix[Length[el[[1]]]]-el[[1]]];

		tuples=Tuples@MapIndexed[If[#1===0,{y[First[#2]]},Range[0,#1-1]/#1]&,Diagonal[D]];
		branes=(V . #&/@tuples//Mod[#,1]&)/.{Mod[a_,1]:>a/;!NumericQ[a]};
		branes=MapIndexed[If[!NumericQ[#1],z[First[#2]],#1]&,#]&/@branes;
		DeleteDuplicates[branes]//Sort
	];
    (**)
    (**) (* INVARIANT METRICS AND MODULI *)
    (**)
    GetInvariantMetric[gen_]:=Module[{d,Dlist,\[Delta]P,c=Global`c,var,nvar,eqs,system,nmoduli,nullspace,moduli,solvec,sol\[Delta]P,coeff},
		d=Length[First@(First@gen)];
		Dlist=Table[gen[[i]][[1]],{i,1,Length@gen}];
		\[Delta]P=Table[Which[i>= j,Subscript[\[Delta]p, i,j],True,Subscript[\[Delta]p, j,i]],{i,1,d},{j,1,d}];
		var=DeleteDuplicates[Flatten[\[Delta]P]];
		nvar=Length[var];
		
		eqs=Flatten@Table[(Transpose[Dlist[[i]]] . \[Delta]P . Dlist[[i]]-\[Delta]P),{i,1,Length[Dlist]}]; (* D^TGD = G *)
		coeff=CoefficientArrays[eqs,var];
		If[Length[coeff]>1,
			system=Normal[CoefficientArrays[eqs,var]][[2]];
			nmoduli=nvar-MatrixRank[system];
			
			nullspace=NullSpace[system];
			moduli=Table[Subscript[c, k],{k,1,Length[nullspace]}];
			solvec=Transpose[nullspace] . moduli;
			sol\[Delta]P=-\[Delta]P/.{(#[[1]]->#[[2]])&/@Transpose[{var,solvec}]//Flatten}//Flatten[#,1]&;,
			
			nmoduli=nvar;
			moduli=Table[Subscript[c, k],{k,1,nvar}];
			sol\[Delta]P=\[Delta]P/.{(#[[1]]->#[[2]])&/@Transpose[{var,moduli}]//Flatten}//Flatten[#,1]&;
		];
		Return[{nmoduli,moduli,sol\[Delta]P/.{Subscript[c, i_]:>-Subscript[c, i]}}];
	]
	(**)
	(**)
	GetModuliSpaceMetric[Dim_,G_,moduli_,print:(_?(BooleanQ[#]&)):False]:=Block[{\[Delta],\[DoubleStruckD],\[Delta]fields,kinterms,g},
		If[Dim-Length[G]<=2,
			Message[GetModuliSpaceMetric::dim];
			Return[$Failed]
		];
	
		\[Delta]fields=\[Delta]/@moduli;
		\[DoubleStruckD][f_]:=Sum[D[f,moduli[[j]]]\[Delta]fields[[j]],{j,1,Length@moduli}];
		kinterms=(1/((Dim-Length[G])-2) (\[DoubleStruckD][Log@Sqrt[Det[#]]])^2+1/4 Tr@MatrixPower[Inverse[#] . \[DoubleStruckD][#],2])&@G//Simplify;
		g=Table[Coefficient[kinterms,#[[i]]#[[j]]],{i,Length[#]},{j,Length[#]}]&@\[Delta]fields//Simplify;
		If[print,Print[kinterms/.{\[Delta][a_]:>"(\[PartialD]"<>ToString[a]<>")"}]];
		Return[1/2 (g+Transpose[g])];
	]
	(**)
	(* INVARIANT FORMS *)
	(**)
	Subscript[dz_, i_]\[TensorWedge]Subscript[dz_, i_]^=0;
	Subscript[dz_, i_]\[TensorWedge]Subscript[dz_, j_]/;!OrderedQ@{i,j}^:=Signature@{i,j} Subscript[dz,#]\[TensorWedge]Subscript[dz,#2]&@@Sort@{i,j}

	Clear[oneforms];
	oneforms[n_]:=Table[Subscript[Global`dz, i],{i,1,n}];
	
	Clear[diffBasis];
	diffBasis[n_]:=Join[{oneforms[n]},Table[Map[TensorWedge@Apply[Sequence,#]&,(Subsets[oneforms[n],{i}]),1],{i,2,n}]];
	
	Clear[rep];
	rep[gen_]:=(#[[1]]->#[[2]])&/@Transpose[{oneforms[Length[gen[[1]]]],gen[[1]] . oneforms[Length[gen[[1]]]]}]//Flatten
	
	Clear[GetInvariantForms];
	GetInvariantForms[gList_?ListQ]:=Module[{k=Length[First[gList][[1]]],dBasis,genform,tgenform,coeff,sys={},sol,invform,Betti,forms},
		invform={1};
		dBasis=diffBasis[k];
		Betti=Join[{1},ConstantArray[0,k]];
		
		For[i=1,i<=k,i++,
			coeff=Table[c[j],{j,1,Length@dBasis[[i]]}]; 
			genform=coeff . (dBasis[[i]]);
			
			sys={};
			For[j=1,j<=Length[gList],j++,
				tgenform=(genform/.rep[gList[[j]]]//TensorExpand);
				AppendTo[sys,If[Length[#]>1,#[[2]],0]]&@Normal[CoefficientArrays[genform-tgenform,dBasis[[i]]]
			];
			];
			sys=Flatten[sys,1];
			
			sol=Solve[sys==0][[1]]; 
			AppendTo[invform,genform/.sol/.{Times[0,TensorWedge[___]]:>0}//Simplify];
			Betti[[i+1]]=Length[coeff]-If[Length[#]>1,MatrixRank@Normal[#[[2]]],0]&@CoefficientArrays[sys];
		];
		forms=(CoefficientList[#,Table[c[a],{a,Binomial[k,Floor[k/2]]}]]//Flatten//DeleteCases[#,0]&)&/@invform;
		Return[{Betti,forms,GetFormCoefficients[forms]}]
	];
	
	Clear[GetFormCoefficients];
	GetFormCoefficients[forms_]:=Block[{formcoeff=Table[{},{i,Length[forms]}],formSparseArray={}},
		AppendTo[formcoeff[[1]],{1->1}];
		AppendTo[formSparseArray,formcoeff[[1]]];
		For[i=2,i<=Length[forms],i++,
			For[j=1,j<=Length[forms[[i]]],j++,
				AppendTo[formcoeff[[i]],forms[[i,j]]/.{Plus->List}/.TensorWedge->List/.(({c_. Table[Subscript[Global`dz, Pattern[#,_]&@#[[n]]],{n,i-1}]:>(#->c)})&@(Table[Unique[],{n,i-1}]))]
			];
			AppendTo[formSparseArray,Flatten[#/. (inds_->val_):>Thread[Permutations[inds]->Signature/@Permutations[inds] val]]&/@formcoeff[[i]]];
		];
		
		Return[formSparseArray];
	];
	(**)
	(* SPIN STRUCTURES & BOUNDARY CONDITIONS *)
	(**)
	Clear[RuleFromList];
	RuleFromList[blist_]:=Module[{cols,reps=<||>,varMap=<||>,varIndex=1,baseCol,equalCols,var},cols=Transpose[blist];
		Do[
			If[KeyExistsQ[reps,i],Continue[]];
			If[AllTrue[cols[[i]],#==0&],reps[i]=0;Continue[];];
			baseCol=cols[[i]];
			equalCols=Select[Range[i,Length[cols]],cols[[#]]===baseCol&];
			var=Subscript[h,i];
			varIndex++;
			Do[reps[j]=var,{j,equalCols}];,
			{i,Length[cols]}
		];
		(*Output rule:{h[1]->h1,h[2]->h1,...}*)
		AssociationThread[Table[h[i],{i,Length[cols]}],Table[reps[i],{i,Length[cols]}]]//Normal
	];
	
	Clear[SpinStructures];
	SpinStructures[group_List]:=Block[{n,h=Global`h,H,spins,allowed,hvec,rule},
		If[!AllTrue[group, MatchQ[#, {_?MatrixQ, _?VectorQ, _?NumericQ}] &],
			Message[SpinStructures::arg];
			Return[$Failed]
		];
		n=Length[(First[group])[[1]]];
		spins=Tuples[{0,1/2},n];
		hvec=Array[h,n];
		H=#[[1]]&/@group;
		
		allowed=Select[spins,AllTrue[Table[Transpose[(IdentityMatrix[n]-H[[j]])] . hvec/.((Flatten[{#[[1]]->#[[2]]}&/@Transpose[{hvec,#}]])),{j,Length[H]}]//Flatten,IntegerQ]&];
		allowed=Select[allowed,AllTrue[(ElementOrder[#](#[[3]]-hvec . #[[2]])&/@group)/.(Flatten[{#[[1]]->#[[2]]}&/@Transpose[{hvec,#}]])//Flatten,EvenQ]&];
		
		rule=RuleFromList[allowed];

		Return[<|
			"GeneralForm" -> hvec/.rule/.{h[a_]:>Subscript[h, a]},
			"Allowed" -> allowed
			|>];
	]
	(**)
	(**)
	(**) (* CYCLIC GROUP FUNCTIONS *)
	(**)
	Clear[GetCompanionMatrix];
    GetCompanionMatrix[p_,x_]:=Module[{n,w=CoefficientList[p,x]},w=-w/Last[w];
		n=Length[w]-1;
		SparseArray[{{i_,n}:>w[[i]],{i_,j_}/;i==j+1->1},{n,n}]
	];
	
	Clear[FiniteOrderMatrices];
	FiniteOrderMatrices[k_?IntegerQ]:=Module[{list,size,plist,polvec,solvec,Mlist,orderlist},
		list={};
		For[n=1,n<=2k^2,n++,
			If[EulerPhi[n]<=k,AppendTo[list,{n,EulerPhi[n]}]];
		];
	
		size=Sum[c[list[[i,1]]]list[[i,2]],{i,1,Length[list]}];
		
		solvec=Solve[Flatten@{size==k,Table[c[list[[i,1]]]>=0,{i,1,Length@list}]},Table[c[list[[i,1]]],{i,Length@list}],Integers];
		
		plist=DeleteCases[#,{a_,0}]&/@(Table[{\[CapitalPhi][list[[i,1]]],c[list[[i,1]]]},{i,1,Length@list}]/. #&/@solvec);
		
		polvec=(Flatten[(Table[#[[1]],{i,1,#[[2]]}]&/@#)]/.\[CapitalPhi][n_]:>Cyclotomic[n,x])&/@plist;
		orderlist=LCM[Evaluate[Sequence@@#]]&/@((Flatten[(Table[#[[1]]/.{\[CapitalPhi][n_]:>n},{i,1,#[[2]]}]&/@#)])&/@plist);
		Mlist=(BlockDiagonalMatrix[GetCompanionMatrix[#,x]&/@#])&/@polvec;
		
		Return[SortBy[{orderlist,Mlist}//Transpose,1/#[[1]]&]];
	];
	(**)
	(**)
	(**) (* TRACE FUNCTIONS *)
	(**)
	Clear[CompleteGeneratorMatrix];
	CompleteGeneratorMatrix::dim = "A `1`-dimensional compact action cannot be embedded in the little group SO(`2`-2). The dimension k of the compact space must satisfy k<=D-2 for a proper little-group embedding.";
	CompleteGeneratorMatrix[M_?MatrixQ,Dim_?IntegerQ]:=(
		If[Dim - 2 < Length[M],
			Message[CompleteGeneratorMatrix::dim,Length[M],Dim];
			Return[$Failed]
		];
		Normal@BlockDiagonalMatrix[{M,IdentityMatrix[(Dim-2)-Length[M]]}]
	);
	
	Clear[TraceSym];
	TraceSym[g_,Dim_?IntegerQ]:=1/2 (Tr[#]^2+Tr[MatrixPower[#,2]])-1&@CompleteGeneratorMatrix[g[[1]],Dim];
	
	Clear[TraceForm];
	TraceForm[k_,g_,Dim_?IntegerQ]:=If[k\[Element]Reals,#,#/2]&@((SeriesCoefficient[#,{x,0,Abs[k]}]&@Product[Exp[-(-x)^l Tr[MatrixPower[#,l]]/l],{l,1,Abs[k]}])&@CompleteGeneratorMatrix[g[[1]],Dim]);

	Clear[TraceSpinor];
	TraceSpinor[g_,Dim_?IntegerQ,Weyl:(_?(BooleanQ[#]&)):False]:=Module[{angles,k,Sp,Sm,S},
		If[EvenQ[Dim],
			k=(Dim-2)/2;
			angles=Join[#,ConstantArray[0,k-Length[#]]]&@(Select[(Arg@Eigenvalues@g[[1]]),#>0&]);

			Sp=Select[Tuples[{1/2,-(1/2)},k],Product[#[[i]],{i,k}]>0&];
			Sm=Select[Tuples[{1/2,-(1/2)},k],Product[#[[i]],{i,k}]<0&];
			Exp[2\[Pi] I g[[3]]](*g[[3]]*)(Total[Exp[I angles . #]&/@Sp]+If[Weyl,0,1]Total[Exp[I angles . #]&/@Sm]//FullSimplify)//Return,
			
			k=(Dim-3)/2;
			angles=Join[#,ConstantArray[0,k-Length[#]]]&@(Select[(Arg@Eigenvalues@g[[1]]),#>0&]);

			S=Tuples[{1/2,-(1/2)},k];
			Exp[2\[Pi] I g[[3]]](*g[[3]]*)(Total[Exp[I angles . #]&/@S]//FullSimplify)//Return
		];
	];

	Clear[TraceRS];
	TraceRS[g_,Dim_?IntegerQ,Weyl:(_?(BooleanQ[#]&)):False]:=((Tr[#]-1)TraceSpinor[g,Dim,Weyl])&@CompleteGeneratorMatrix[g[[1]],Dim];

	Clear[TraceBosonicField];
	TraceBosonicField[field_Association, g_, dim_Integer] := Lookup[field, "Multiplicity", 1] Switch[
			Lookup[field, "Type", Missing["Type"]],
				"Graviton", TraceSym[g, dim],
				"Scalar", TraceForm[0, g, dim],
				"Form", With[{rank = Lookup[field, "Rank", Missing["Rank"]], selfDual = TrueQ[Lookup[field, "SelfDual", False]]}, 
							TraceForm[If[selfDual, I rank, rank], g, dim]
						],
				_, Message[TraceBosons::type,Lookup[field, "Type"]]; $Failed
    ];

	Clear[TraceFermionicField];
	TraceFermionicField[field_Association, g_, dim_Integer] := Lookup[field, "Multiplicity", 1] Switch[
			Lookup[field, "Type", Missing["Type"]],
				"Spinor", TraceSpinor[g,dim,Lookup[field, "Weyl", False]],
				"Gravitino", TraceRS[g,dim,Lookup[field, "Weyl", False]],
				_,Message[TraceFermions::type,Lookup[field, "Type"]];$Failed
	];

	Clear[TraceBosons,TraceFermions]
	TraceBosons[bosons_?(AllTrue[#,AssociationQ[#]&]&),g_,Dim_?IntegerQ]:=TraceBosons[bosons,g,Dim]=(
		If[!(MatchQ[g, {_?MatrixQ, _?VectorQ, _?NumericQ}]),Message[TraceBosons::arg];Return[$Failed]];
		Total[TraceBosonicField[#,g,Dim]&/@bosons]);
	TraceBosons[bosons_List,g_,Dim_?IntegerQ]:=TraceBosons[bosons,g,Dim]=If[bosons=={},0,bosons[[1]]TraceSym[g,Dim]+Sum[TraceForm[bosons[[i]],g,Dim],{i,2,Length[bosons]}]];

	TraceFermions[fermions_?(AllTrue[#,AssociationQ[#]&]&),g_,Dim_?IntegerQ]:=TraceFermions[fermions,g,Dim]=(
		If[!(MatchQ[g, {_?MatrixQ, _?VectorQ, _?NumericQ}]),Message[TraceFermions::arg];Return[$Failed]];
		Total[TraceFermionicField[#,g,Dim]&/@fermions]);
	TraceFermions[fermions_List,g_,Dim_?IntegerQ]:=TraceFermions[fermions,g,Dim]=If[fermions=={},0,Sum[
		If[Abs[fermions[[i]]]==3/2,
		TraceRS[g,Dim,!RealValuedNumberQ[fermions[[i]]]],
		TraceSpinor[g,Dim,!RealValuedNumberQ[fermions[[i]]]]],{i,1,Length[fermions]}
	]];
	(**)
	(**)
	(**)(* LATTICE SUMS FUNCTIONS  *)
	(**)
	Clear[GetEwaldLatticeByNorm];
	GetEwaldLatticeByNorm[r2w_,Gw_,bw_]:=GetEwaldLatticeByNorm[r2w,Gw,bw]=Block[{d=Length[Gw],r2=N[r2w],G=N[Gw],b=N[bw],s,nrange,r2new,Gnew,bnew,result},
			
		(*If the remaining budget is negative (even slightly, from round-off), there are no lattice points here*)
		If[r2 < 10^-8, Return[{}]];
		
		(*In dimension 1, we are done quickly*)
		If[d==1,Return[Range@@{Ceiling[-Sqrt[(r2/G[[1,1]])]-b[[1]]],Floor[Sqrt[r2/G[[1,1]]]-b[[1]]]}]]; 
	
		s=G[[1,1]]-G[[1,2;;]] . Inverse[G[[2;;,2;;]]] . G[[1,2;;]]; (* Schur complement *)
		nrange=Range@@{Ceiling[-#-b[[1]]],Floor[#-b[[1]]]}&@If[s>0,Sqrt[r2/s],Sqrt[r2/G[[1,1]]]]; (* Range in selected coordinate *)
		(* Define reduced quantities 1 dimension below *)
		Gnew=G[[2;;,2;;]];
		bnew[n_]:=(b[[2;;]]+(n+b[[1]]) Inverse[G[[2;;,2;;]]] . G[[1,2;;]]);
		r2new[n_]:=(r2-(n+b[[1]])^2 (G[[1,1]]-G[[1,2;;]] . Inverse[G[[2;;,2;;]]] . G[[1,2;;]]));
		
		result={#,GetEwaldLatticeByNorm[r2new[#],Gnew,bnew[#]]}&/@nrange; (* For each n, determine remaining coordinates recursively *)
		Return[Table[Flatten@{#[[1]],#[[2,i]]},{i,Length[#[[2]]]}]&/@result//Flatten[#,1]&]; 
	]
	Clear[GetEwaldCutoffs];
	GetEwaldCutoffs[k_, s_, alpha_, detG_, eps_] := Module[{p, A1, A2, C1, C2, arg1, arg2, rmaxn, rmaxk,\[Rho], fallback = 8.0},

		  rmaxn =Quiet@Check[\[Rho]/.FindRoot[(2 alpha^s \[Pi]^(k/2) \[Rho]^(k/2) (ExpIntegralE[1-k/2,alpha \[Rho]]-ExpIntegralE[1-s,alpha \[Rho]]))/(Sqrt[detG] (k-2 s) Gamma[k/2] Gamma[s])==eps/2,{\[Rho],1,3}],
		     fallback];
		  rmaxn = If[NumericQ[rmaxn] && rmaxn > 0, rmaxn, fallback];
		  
		  rmaxk = Quiet@Check[\[Rho]/.FindRoot[(alpha^s Gamma[k/2,(\[Pi]^2 \[Rho])/alpha]-\[Pi]^(2 s) \[Rho]^s Gamma[k/2-s,(\[Pi]^2 \[Rho])/alpha])/(Gamma[k/2] Gamma[1+s])==eps/2,{\[Rho],1,3}],
		     fallback];
		  rmaxk = If[NumericQ[rmaxk] && rmaxk > 0, rmaxk, fallback];
		
		  {rmaxn, rmaxk}
		  ];
	
	Clear[EwaldKernel];
	EwaldKernel=Compile[{{c,_Real,1},{h,_Real,1},{s,_Real},{alpha,_Real},{G,_Real,2},{Ginv,_Real,2},{points,_Real,2},{pointsk,_Real,2}},
		Module[{k,tot,totk,isum,i,j,vecN,veck,vecNpc,veckmh,sum1Re=0.0,sum1Im=0.0,sum2Re=0.0,sum2Im=0.0,c1Re=0.0,c1Im=0.0,yRe,tRe,yIm,tIm,c2Re=0.0,c2Im=0.0,norm1,norm2,dot1,dot2,tmpRe,tmpIm,pi=N[Pi],Gammas,kinv},
		
		k=Length[c];
		tot=Length[points];
		totk=Length[pointsk];
		Gammas=N[Gamma[s]];
		kinv=k/2.0-s;
		
		(*----First sum----*)
		For[isum=1,isum<=tot,isum++,vecN=points[[isum]];vecNpc=vecN+c;norm1=0.0;
			For[i=1,i<=k,i++,For[j=1,j<=k,j++,norm1+=(vecNpc[[i]])*G[[i,j]]*(vecNpc[[j]]);];];
			If[norm1>1. 10^-14,dot1=0.0;
				For[i=1,i<=k,i++,dot1+=h[[i]]*vecN[[i]];];
				tmpRe=Cos[2.0*pi*dot1];tmpIm=Sin[2.0*pi*dot1];
				norm1=norm1^(-s)*Gamma[s,alpha*norm1]/Gammas;
				sum1Re+=tmpRe*norm1;sum1Im+=tmpIm*norm1;
			];
		];
		(*----Second sum----*)
		For[isum=1,isum<=totk,isum++,veck=pointsk[[isum]];veckmh=veck-h;norm2=0.0;
			For[i=1,i<=k,i++,For[j=1,j<=k,j++,norm2+=(veckmh[[i]])*Ginv[[i,j]]*(veckmh[[j]]);];];
			If[norm2>1. 10^-14,dot2=0.0;
				For[i=1,i<=k,i++,dot2+=(veckmh[[i]])*c[[i]];];
				tmpRe=Cos[2.0*pi*dot2];
				tmpIm=Sin[2.0*pi*dot2];
				norm2=Gamma[kinv,(pi*pi*norm2)/alpha]/norm2^(kinv);
				sum2Re+=tmpRe*norm2;
				sum2Im+=-tmpIm*norm2;
			];
		];
		{sum1Re+sum1Im,sum2Re+sum2Im}],
		CompilationTarget->"C",RuntimeOptions->"Speed"];
		
	Clear[Ewald];
	Ewald[c0_?VectorQ,h0_?VectorQ,s0_?NumericQ,alpha0_?NumericQ,G0_?MatrixQ,\[Epsilon]_?NumericQ]:=Block[{k=Length[c0],rmaxn,rmaxk,Ginv,detG,normG,normGdual,deltaTerm,offsetTerm,points,pointsk,tot,sumvec,vecN,isum,
		(* Make everything floating point -- $MachinePrecision *)
		vecs,rminn,rmink,
		c=N[c0],s=N[s0],h=N[h0],G=N[G0,10],alpha=N[alpha0],pi=N[Pi],Ne},
	
		(* Inverse and determinant of metric *)
		Ginv=Inverse[G];
		detG=Det[G];
		
		(* Cutoff for both sums from accuracy parameter \[Epsilon] *)
		{rmaxn, rmaxk} = GetEwaldCutoffs[k, s, alpha, detG, \[Epsilon]/2];
		
		(* Generating lattices of vectors with norm less than cutoffs *)
		points=N[GetEwaldLatticeByNorm[rmaxn,G,c]];
		pointsk=N[GetEwaldLatticeByNorm[rmaxk,Ginv,-h]];
		
		If[k==1,points={#}&/@points;pointsk={#}&/@pointsk;];(* Handles slightly different format for k 1 *)
		
		(*Do the sums via a For over the entries of points*)
		sumvec={0,0}; 
		sumvec+=EwaldKernel[c,h,s,alpha,G,Ginv,points,pointsk];
		sumvec[[2]]*=pi^(2 s-k/2)/(Gamma[s] Sqrt[detG]);
		
		(*KRONECKER DELTA term: only added if h=0-vector *)
		deltaTerm=If[h==ConstantArray[0,k],(pi^(k/2) alpha^(s-k/2))/(Sqrt[detG] Gamma[s] (s-k/2)),0];		
		
		(*Offset term: only included if the vector c is all of integer coordinates *)
		offsetTerm=If[And@@IntegerQ/@c0,-((alpha^s Exp[-2 pi I (h . c)])/Gamma[1+s]),0];
		
		(*SUM all contributions*)
		Return[Chop[Total[sumvec]+deltaTerm+offsetTerm]];
	];

	Clear[ReducedLatticeSum];
	ReducedLatticeSum[Dim_?IntegerQ,el_,hvec_?VectorQ,G_?MatrixQ,\[Epsilon]_:1*^-4]:=Block[{s=Dim/2,k=Length[G],Dg=el[[1]],sp,kp,Gp,V,M,Vinv,bgp,vg,\[Eta]vec=Table[\[Eta][i],{i,Length[hvec]}],\[Beta]vec,dvec,sum,\[Alpha],precision=N[\[Epsilon]]},
		If[!AllTrue[G,NumericQ,2] || !PositiveDefiniteMatrixQ[G],
			Message[ReducedLatticeSum::metric];
			Return[$Failed];
		];

		\[Alpha]=N[\[Pi](Det[G]^(-1/k))];
		
		(* V = Matrix whose columns are the basis vectors of the null space of ((1-Subscript[D, g])^T) -- Transposed because NullSpace gives the vectors in rows *)
		{V,kp}={Transpose[#],Length[#]}&@(NullSpace[Transpose@(IdentityMatrix[k]-Dg)]);
		
		(* M = Matrix whose columns are the basis vectors of the null space of (1-Subscript[D, g]) -- Transposed because NullSpace gives the vectors in rows *)
		M=If[IdentityMatrix[k]==Dg,IdentityMatrix[k],Transpose@(NullSpace[(IdentityMatrix[k]-Dg)])];
		
		If[M=={},Return[0.]]; (* There is no invariant subspace -- The lattice sum vanishes *)
		
		Vinv=Transpose@M; 
		sp=s+(kp-k)/2;
		Gp=Vinv . (G . Transpose[Vinv]);
		
		bgp=(# . Inverse[(Transpose[#] . #)] . Transpose[#]&@M) . el[[2]];
		vg=Transpose[V] . bgp; 
		
		If[#=={},Return[sum=0], 
			\[Beta]vec=(hvec-\[Eta]vec)/.#[[1]]; 
			dvec=Vinv . \[Beta]vec; 
			sum=Sqrt[Det[Gp]]((\[Pi]^((k-kp)/2) Gamma[sp])/Gamma[s])Ewald[vg,dvec,sp,\[Alpha],Gp,precision];
			Return[sum]
		]&@If[IdentityMatrix[k]==Dg,{Table[\[Eta][i]->0,{i,Length[\[Eta]vec]}]},FindInstance[{(Transpose[IdentityMatrix[k]-Dg]) . (\[Eta]vec-hvec)==0,AllTrue[\[Eta]vec,#\[Element]Integers&]},\[Eta]vec]]
	];
	
	Clear[TracedSum];
	TracedSum[Dim_?NumericQ,el_,spectrum_,hvec_?VectorQ,G_?MatrixQ,saddle_,\[Epsilon]_:1*^-4]:=Block[{sum=0,Geval,detG=Det[G/.saddle],k=Length[G],subspec},
		Geval=(G/(detG)^(1/k)/.saddle);
		If[!AllTrue[Geval,NumericQ,2] || !PositiveDefiniteMatrixQ[Geval],
			Message[TracedSum::metric];
			Return[$Failed];
		];
		If[AssociationQ[spectrum],
			(*Association*)
			If[Lookup[spectrum,"Bosons",{}]!={},
				subspec = KeyValueMap[{#2,#1}&,GroupBy[spectrum["Bosons"],Lookup[#,"TwistedBoundaryConditions",ConstantArray[0,k]]&]];
				sum+=Total[(TraceBosons[#[[1]],el,Dim]ReducedLatticeSum[Dim,el,#[[2]],Geval,\[Epsilon]]&/@subspec)]
				];		
			If[Lookup[spectrum,"Fermions",{}]!={},
				subspec = KeyValueMap[{#2,#1}&,GroupBy[spectrum["Fermions"],Lookup[#,"TwistedBoundaryConditions",hvec]&]];
				sum+=(-1)Total[(TraceFermions[#[[1]],el,Dim]ReducedLatticeSum[Dim,el,#[[2]],Geval,\[Epsilon]]&/@subspec)]
				];,
			(*List*)
			If[spectrum[[1]]!={},sum+=TraceBosons[spectrum[[1]],el,Dim]ReducedLatticeSum[Dim,el,ConstantArray[0,k],Geval,\[Epsilon]]];		
			If[spectrum[[2]]!={},sum+=(-1)TraceFermions[spectrum[[2]],el,Dim]ReducedLatticeSum[Dim,el,hvec,Geval,\[Epsilon]]];
		];
		Return[detG^(1/2-(Dim/2)/k) sum//Re];
	];
	(**)
	(**)
	(**)(* CASIMIR POTENTIAL FUNCTIONS *)
	(**)
	Clear[CasimirPotential];
	CasimirPotential[Dim_?NumericQ,group_?ListQ,spectrum_,hvec_?VectorQ,G_?MatrixQ,saddle_,\[Epsilon]_:1*^-4]:=
		(Gamma[(Dim)/2]/(2\[Pi]^(Dim/2))) 1/Length[group] (Sum[TracedSum[Dim,group[[i]],spectrum,hvec,G,saddle,\[Epsilon]],{i,Length[group]}]);
	(**)
	Clear[CasimirEnergyDensity];
	CasimirEnergyDensity[Dim_?IntegerQ,group_?ListQ,spectrum_,hvec_?VectorQ,G_?MatrixQ,saddle_,zvec_?(VectorQ[#,NumericQ]&),\[Epsilon]_:1*^-4]:=Module[{cvec,k=Length[G],Geval,sum=0,subspec},
		cvec[g_]:=(IdentityMatrix[k]-g[[1]]) . zvec-g[[2]];
		Geval=G/(Det[G])^(1/k)/.saddle;
		If[!AllTrue[Geval,NumericQ,2] || !PositiveDefiniteMatrixQ[Geval],
			Message[CasimirEnergyDensity::metric];
			Return[$Failed];
		];
		
		If[AssociationQ[spectrum],
			(*Association*)
			If[Lookup[spectrum,"Bosons",{}]!={},
				subspec = KeyValueMap[{#2,#1}&,GroupBy[spectrum["Bosons"],Lookup[#,"TwistedBoundaryConditions",ConstantArray[0,k]]&]];
				sum+=Total[(Sum[TraceBosons[#[[1]],group[[i]],Dim]Ewald[cvec@group[[i]],#[[2]],Dim/2,\[Pi],Geval,\[Epsilon]],{i,Length@group}]&/@subspec)]
				];		
			If[Lookup[spectrum,"Fermions",{}]!={},
				subspec = KeyValueMap[{#2,#1}&,GroupBy[spectrum["Fermions"],Lookup[#,"TwistedBoundaryConditions",hvec]&]];
				sum+=(-1)Total[(Sum[TraceFermions[#[[1]],group[[i]],Dim]Ewald[cvec@group[[i]],#[[2]],Dim/2,\[Pi],Geval,\[Epsilon]],{i,Length@group}]&/@subspec)]
				];,
			(*List*)
			 If[spectrum[[1]]!={},sum += Sum[TraceBosons[spectrum[[1]],group[[i]],Dim]Ewald[cvec@group[[i]],ConstantArray[0,k],Dim/2,\[Pi],Geval,\[Epsilon]],{i,Length@group}]];
			 If[spectrum[[2]]!={},sum += -Sum[TraceFermions[spectrum[[2]],group[[i]],Dim]Ewald[cvec@group[[i]],hvec,Dim/2,\[Pi],Geval,\[Epsilon]],{i,Length@group}]];
		];
		Return[Gamma[Dim/2]/(2\[Pi]^(Dim/2)) Det[G]^(-(Dim/2)/k)sum/.saddle];
	]
	(**)
	(**)
	Clear[RFMGrad];
	RFMGrad[V_, point_, eps_ : 1*^-4] := Module[{k = Length[point], dx},
		DistributeDefinitions[eps, k];
		1/V[point] ParallelTable[
			If[point[[i]] == 0, dx = eps, dx = eps point[[i]]];
			(V[point + dx #] - V[point - dx #])/(2 dx) &@SparseArray[{i} -> 1, k], {i, k}
			]
	];
	
	Clear[RFMHessian];
	RFMHessian[f_,x_,eps_:1*^-4]:=Module[{H,dx,n=Length[x],f0},
		H=ConstantArray[0,{n,n}];
		If[!(MatchQ[eps,_?NumericQ]||AllTrue[eps,MatchQ[#,_?NumericQ]&]),
			Message[RFMHessian::arg];
			Return[$Failed]
		];
		If[MatchQ[eps,VectorQ],dx=DiagonalMatrix[eps],dx=DiagonalMatrix[ConstantArray[eps,n]]];
		f0=f[x];

		DistributeDefinitions[dx,f,x];
		H=ParallelTable[
			If[i==j,
				1/2 (4 f0+f[-4 dx[[i]] +x]-3 (f[-2 dx[[i]]+x]+f[2 dx[[i]]+x])+f[4 dx[[i]]+x])/(4 dx[[i,i]]^2),
				If[i<=j,1/(4 dx[[i,i]]dx[[j,j]]) (-f[2 dx[[i]]-2 dx[[j]]+x]-3 f[-dx[[i]]-dx[[j]]+x]+3 f[dx[[i]]-dx[[j]]+x]+3 f[-dx[[i]]+dx[[j]]+x]-3 f[dx[[i]]+dx[[j]]+x]-f[-2 dx[[i]]+2 dx[[j]]+x]+f[-2 (dx[[i]]+dx[[j]])+x]+f[2 (dx[[i]]+dx[[j]])+x]),0]
			],{i,n},{j,n}];
		Return[(H+Transpose[H])]
	];
	
End[]

EndPackage[]

